# TCL File Generated by Component Editor 16.1
# Wed Jan 31 16:58:46 GMT+08:00 2018
# DO NOT MODIFY

# 
# harden_sync "harden_sync" v1.0
# FACC 5G 2018.05.17.16:58:46
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1

# 
# module harden_sync
# 
set_module_property DESCRIPTION ""
set_module_property NAME harden_sync_eth
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "FACC 5G"
set_module_property AUTHOR "XJ.Z"
set_module_property DISPLAY_NAME harden_sync_eth
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false



# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL harden_sync
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file harden_sync.v VERILOG PATH harden_sync.v TOP_LEVEL_FILE
add_fileset_file sync.v VERILOG PATH sync.v


# 
# parameters
# 
add_parameter FFT_SIZE INTEGER 4096
set_parameter_property FFT_SIZE DEFAULT_VALUE 4096
set_parameter_property FFT_SIZE DISPLAY_NAME FFT_SIZE
set_parameter_property FFT_SIZE TYPE INTEGER
set_parameter_property FFT_SIZE UNITS None
set_parameter_property FFT_SIZE HDL_PARAMETER true

add_parameter CP_LEN1 INTEGER 352
set_parameter_property CP_LEN1 DEFAULT_VALUE 352
set_parameter_property CP_LEN1 DISPLAY_NAME CP_LEN1
set_parameter_property CP_LEN1 TYPE INTEGER
set_parameter_property CP_LEN1 UNITS None
set_parameter_property CP_LEN1 HDL_PARAMETER true

add_parameter CP_LEN2 INTEGER 288
set_parameter_property CP_LEN2 DEFAULT_VALUE 288
set_parameter_property CP_LEN2 DISPLAY_NAME CP_LEN2
set_parameter_property CP_LEN2 TYPE INTEGER
set_parameter_property CP_LEN2 UNITS None
set_parameter_property CP_LEN2 HDL_PARAMETER true

add_parameter TX_FREQ INTEGER 61440000                                       
set_parameter_property TX_FREQ DEFAULT_VALUE 61440000                        
set_parameter_property TX_FREQ DISPLAY_NAME TX_FREQ                          
set_parameter_property TX_FREQ TYPE INTEGER                                  
set_parameter_property TX_FREQ UNITS None                                    
set_parameter_property TX_FREQ HDL_PARAMETER true                            

add_parameter RX_FREQ INTEGER 122880000                              
set_parameter_property RX_FREQ DEFAULT_VALUE 122880000               
set_parameter_property RX_FREQ DISPLAY_NAME TX_FREQ                 
set_parameter_property RX_FREQ TYPE INTEGER                         
set_parameter_property RX_FREQ UNITS None                           
set_parameter_property RX_FREQ HDL_PARAMETER true                   


# 
# display items
# 

#                                                                
# connection point clock                                         
#                                                                
add_interface clk_tx clock end                                   
set_interface_property clk_tx clockRate 0                        
set_interface_property clk_tx ENABLED true                       
set_interface_property clk_tx EXPORT_OF ""                       
set_interface_property clk_tx PORT_NAME_MAP ""                   
set_interface_property clk_tx CMSIS_SVD_VARIABLES ""             
set_interface_property clk_tx SVD_ADDRESS_GROUP ""               
                                                                 
add_interface_port clk_tx clk_tx clk Input 1                     

# 
# connection point clock
# 
add_interface clk_rx clock end
set_interface_property clk_rx clockRate 0
set_interface_property clk_rx ENABLED true
set_interface_property clk_rx EXPORT_OF ""
set_interface_property clk_rx PORT_NAME_MAP ""
set_interface_property clk_rx CMSIS_SVD_VARIABLES ""
set_interface_property clk_rx SVD_ADDRESS_GROUP ""

add_interface_port clk_rx clk_rx clk Input 1


# 
# connection point rst_n
# 
add_interface rst_n reset end
set_interface_property rst_n associatedClock ""
set_interface_property rst_n synchronousEdges NONE
set_interface_property rst_n ENABLED true
set_interface_property rst_n EXPORT_OF ""
set_interface_property rst_n PORT_NAME_MAP ""
set_interface_property rst_n CMSIS_SVD_VARIABLES ""
set_interface_property rst_n SVD_ADDRESS_GROUP ""

add_interface_port rst_n rst_n reset_n Input 1

# 
# connection point pps_in
# 
add_interface pps_in conduit end
set_interface_property pps_in associatedClock ""
set_interface_property pps_in associatedReset ""
set_interface_property pps_in ENABLED true
set_interface_property pps_in EXPORT_OF ""
set_interface_property pps_in PORT_NAME_MAP ""
set_interface_property pps_in CMSIS_SVD_VARIABLES ""
set_interface_property pps_in SVD_ADDRESS_GROUP ""

add_interface_port pps_in pps_in export Input 1


# 
# connection point sync_ctrl
# 
add_interface sync_ctrl conduit end
set_interface_property sync_ctrl associatedClock ""
set_interface_property sync_ctrl associatedReset ""
set_interface_property sync_ctrl ENABLED true
set_interface_property sync_ctrl EXPORT_OF ""
set_interface_property sync_ctrl PORT_NAME_MAP ""
set_interface_property sync_ctrl CMSIS_SVD_VARIABLES ""
set_interface_property sync_ctrl SVD_ADDRESS_GROUP ""

add_interface_port sync_ctrl sync_ctrl export_0 Input 32
add_interface_port sync_ctrl tx_time   export_1 Input 32
add_interface_port sync_ctrl rx_time   export_2 Input 32


#                                                                                
# connection point tx_sync_ctrl                                                  
#                                                                                
add_interface tx_sync_ctrl conduit end                                           
set_interface_property tx_sync_ctrl associatedClock ""                           
set_interface_property tx_sync_ctrl associatedReset ""                           
set_interface_property tx_sync_ctrl ENABLED true                                 
set_interface_property tx_sync_ctrl EXPORT_OF ""                                 
set_interface_property tx_sync_ctrl PORT_NAME_MAP ""                             
set_interface_property tx_sync_ctrl CMSIS_SVD_VARIABLES ""                       
set_interface_property tx_sync_ctrl SVD_ADDRESS_GROUP ""                         
                                                                                 
add_interface_port tx_sync_ctrl tx_trigger trigger Output 1                      
add_interface_port tx_sync_ctrl tx_lcp  lcp Output 1                                                      
add_interface_port tx_sync_ctrl tx_symbol_cnt symbol Output 4                     
add_interface_port tx_sync_ctrl tx_slot_cnt slot Output 8                         
add_interface_port tx_sync_ctrl tx_frame_cnt frame Output 10                      
  

# 
# connection point rx_sync_ctrl
# 
add_interface rx_sync_ctrl conduit end
set_interface_property rx_sync_ctrl associatedClock ""
set_interface_property rx_sync_ctrl associatedReset ""
set_interface_property rx_sync_ctrl ENABLED true
set_interface_property rx_sync_ctrl EXPORT_OF ""
set_interface_property rx_sync_ctrl PORT_NAME_MAP ""
set_interface_property rx_sync_ctrl CMSIS_SVD_VARIABLES ""
set_interface_property rx_sync_ctrl SVD_ADDRESS_GROUP ""

add_interface_port rx_sync_ctrl rx_trigger trigger Output 1
add_interface_port rx_sync_ctrl rx_lcp  lcp Output 1
add_interface_port rx_sync_ctrl mode  mode  Output 1
add_interface_port rx_sync_ctrl rx_symbol_cnt symbol Output 4  
add_interface_port rx_sync_ctrl rx_slot_cnt slot Output 8  
add_interface_port rx_sync_ctrl rx_frame_cnt frame Output 10   


#                                                                         
# connection point irq_1ms                                                
#                                                                         
add_interface irq_1ms conduit end                                         
set_interface_property irq_1ms associatedClock ""                         
set_interface_property irq_1ms associatedReset ""                         
set_interface_property irq_1ms ENABLED true                               
set_interface_property irq_1ms EXPORT_OF ""                               
set_interface_property irq_1ms PORT_NAME_MAP ""                           
set_interface_property irq_1ms CMSIS_SVD_VARIABLES ""                     
set_interface_property irq_1ms SVD_ADDRESS_GROUP ""                       
                                                                          
add_interface_port irq_1ms irq_1ms export Output 1                        
                     
                     
#                                                                         
# connection point sync_abs_index                                                
#                                                                         
add_interface sync_abs_index conduit end                                         
set_interface_property sync_abs_index associatedClock ""                         
set_interface_property sync_abs_index associatedReset ""                         
set_interface_property sync_abs_index ENABLED true                               
set_interface_property sync_abs_index EXPORT_OF ""                               
set_interface_property sync_abs_index PORT_NAME_MAP ""                           
set_interface_property sync_abs_index CMSIS_SVD_VARIABLES ""                     
set_interface_property sync_abs_index SVD_ADDRESS_GROUP ""                       
                                                                          
add_interface_port sync_abs_index slot_cnt_abs slot Output 8  
add_interface_port sync_abs_index frame_cnt_abs frame Output 16  


#                                                                                 
# connection point ante_switch                                                    
#                                                                                 
add_interface ante_switch conduit end                                             
set_interface_property ante_switch associatedClock ""                             
set_interface_property ante_switch associatedReset ""                             
set_interface_property ante_switch ENABLED true                                   
set_interface_property ante_switch EXPORT_OF ""                                   
set_interface_property ante_switch PORT_NAME_MAP ""                               
set_interface_property ante_switch CMSIS_SVD_VARIABLES ""                         
set_interface_property ante_switch SVD_ADDRESS_GROUP ""                           
                                                                                  
add_interface_port ante_switch ante_enable enable Output 1                        
add_interface_port ante_switch ante0_switch ante0 Output 1                        
add_interface_port ante_switch ante1_switch ante1 Output 1                        
                                                                                  
                                                                                  
