# TCL File Generated by Component Editor 16.1
# Fri Apr 13 14:14:00 GMT+08:00 2018
# DO NOT MODIFY


# 
# avlmm_in "avlmm_in" v1.0
#  2018.05.21.14:14:00
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module xg_ethernet
# 
set_module_property DESCRIPTION ""
set_module_property NAME avlmm_in
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "FACC 5G"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME avlmm_in
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avlmm_in
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avlmm_in.sv SYSTEM_VERILOG PATH avlmm_in.sv TOP_LEVEL_FILE



# 
# parameters
# 
add_parameter WORD_WIDTH INTEGER 32
set_parameter_property WORD_WIDTH DEFAULT_VALUE 32
set_parameter_property WORD_WIDTH DISPLAY_NAME WORD_WIDTH
set_parameter_property WORD_WIDTH TYPE INTEGER
set_parameter_property WORD_WIDTH UNITS None
set_parameter_property WORD_WIDTH HDL_PARAMETER true

# 
# parameters
# 
add_parameter WORD_QTY INTEGER 10
set_parameter_property WORD_QTY DEFAULT_VALUE 10
set_parameter_property WORD_QTY DISPLAY_NAME WORD_QTY
set_parameter_property WORD_QTY TYPE INTEGER
set_parameter_property WORD_QTY UNITS None
set_parameter_property WORD_QTY HDL_PARAMETER true

# 
# parameters
# 
add_parameter ADDR_WIDTH INTEGER 4
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 4
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH TYPE INTEGER
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH HDL_PARAMETER true

# 
# display items
# 


# 
# connection point clock
# 
#################################################################                     
                                                                   
#                                                                  
# connection point clk                                          
#                                                                  
add_interface clk clock end                                     
set_interface_property clk clockRate 0                          
set_interface_property clk ENABLED true                         
set_interface_property clk EXPORT_OF ""                         
set_interface_property clk PORT_NAME_MAP ""                     
set_interface_property clk CMSIS_SVD_VARIABLES ""               
set_interface_property clk SVD_ADDRESS_GROUP ""                 
                                                                   
add_interface_port clk clk clk Input 1   

                                                         
# rst_n                                                                                     
add_interface rst_n reset end                                                        
set_interface_property rst_n associatedClock clk                              
set_interface_property rst_n synchronousEdges DEASSERT                               
set_interface_property rst_n ENABLED true                                            
set_interface_property rst_n EXPORT_OF ""                                            
set_interface_property rst_n PORT_NAME_MAP ""                                        
set_interface_property rst_n CMSIS_SVD_VARIABLES ""                                  
set_interface_property rst_n SVD_ADDRESS_GROUP ""                                    
                                                                                            
add_interface_port rst_n rst_n reset_n Input 1                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

#                                                             
# avalon_mm                                                         
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
 
add_interface avalon_mm avalon end                                                                                                                                                                                                                                                                                                                                                           
set_interface_property avalon_mm addressUnits WORDS                                                                                                                                                                                                                                                                                                                                          
set_interface_property avalon_mm associatedClock "clk"                                                                                                                                                                                                                                                                                                                                
set_interface_property avalon_mm associatedReset "rst_n"                                                                                                                                                                                                                                                                                                                              
set_interface_property avalon_mm bitsPerSymbol 8                                                                                                                                                                                                                                                                                                                                             
set_interface_property avalon_mm burstOnBurstBoundariesOnly false                                                                                                                                                                                                                                                                                                                            
set_interface_property avalon_mm burstcountUnits WORDS                                                                                                                                                                                                                                                                                                                                       
set_interface_property avalon_mm explicitAddressSpan 0                                                                                                                                                                                                                                                                                                                                       
set_interface_property avalon_mm holdTime 0                                                                                                                                                                                                                                                                                                                                                  
set_interface_property avalon_mm linewrapBursts false                                                                                                                                                                                                                                                                                                                                        
set_interface_property avalon_mm maximumPendingReadTransactions 0                                                                                                                                                                                                                                                                                                                            
set_interface_property avalon_mm maximumPendingWriteTransactions 0                                                                                                                                                                                                                                                                                                                           
set_interface_property avalon_mm readLatency 1                                                                                                                                                                                                                                                                                                                                               
set_interface_property avalon_mm readWaitTime 1                                                                                                                                                                                                                                                                                                                                              
set_interface_property avalon_mm setupTime 0                                                                                                                                                                                                                                                                                                                                                 
set_interface_property avalon_mm timingUnits Cycles                                                                                                                                                                                                                                                                                                                                          
set_interface_property avalon_mm writeWaitTime 0                                                                                                                                                                                                                                                                                                                                             
set_interface_property avalon_mm ENABLED true                                                                                                                                                                                                                                                                                                                                                
set_interface_property avalon_mm EXPORT_OF ""                                                                                                                                                                                                                                                                                                                                                
set_interface_property avalon_mm PORT_NAME_MAP ""                                                                                                                                                                                                                                                                                                                                            
set_interface_property avalon_mm CMSIS_SVD_VARIABLES ""                                                                                                                                                                                                                                                                                                                                      
set_interface_property avalon_mm SVD_ADDRESS_GROUP ""                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                      
add_interface_port avalon_mm address address Input ADDR_WIDTH                                                                                                                                                                                                                                                                                                                 
add_interface_port avalon_mm read read Input 1                                                                                                                                                                                                                                                                                                                            
add_interface_port avalon_mm readdata readdata Output WORD_WIDTH                                                                                                                                                                                                                                                                                                                  
add_interface_port avalon_mm waitrequest waitrequest Output 1                                                                                                                                                                                                                                                                                                             
add_interface_port avalon_mm write write Input 1                                                                                                                                                                                                                                                                                                                          
add_interface_port avalon_mm writedata writedata Input WORD_WIDTH


#                                                                            
# harden_tx_status                                                                  
#                                                                            
add_interface harden_tx_status conduit end                                           
set_interface_property harden_tx_status associatedClock  ""                          
set_interface_property harden_tx_status associatedReset ""                           
set_interface_property harden_tx_status ENABLED true                                 
set_interface_property harden_tx_status EXPORT_OF ""                                 
set_interface_property harden_tx_status PORT_NAME_MAP ""                             
set_interface_property harden_tx_status CMSIS_SVD_VARIABLES ""                       
set_interface_property harden_tx_status SVD_ADDRESS_GROUP ""                         
                                                                             
add_interface_port harden_tx_status data_in_0 export_0 Input 32 
add_interface_port harden_tx_status data_in_1 export_1 Input 32 
add_interface_port harden_tx_status data_in_2 export_2 Input 32 
add_interface_port harden_tx_status data_in_3 export_3 Input 32 
add_interface_port harden_tx_status data_in_4 export_4 Input 32 
add_interface_port harden_tx_status data_in_5 export_5 Input 32 
 
                                 
#                                                                                         
# harden_rx_status                                                                          
#                                                                                         
add_interface harden_rx_status conduit end                                                
set_interface_property harden_rx_status associatedClock  ""                               
set_interface_property harden_rx_status associatedReset ""                                
set_interface_property harden_rx_status ENABLED true                                      
set_interface_property harden_rx_status EXPORT_OF ""                                      
set_interface_property harden_rx_status PORT_NAME_MAP ""                                  
set_interface_property harden_rx_status CMSIS_SVD_VARIABLES ""                            
set_interface_property harden_rx_status SVD_ADDRESS_GROUP ""                              
                                                                                          
add_interface_port harden_rx_status data_in_6 export_0 Input 32   
add_interface_port harden_rx_status data_in_7 export_1 Input 32               


         
                            
                                                                                             
                                                                                             
         
         
         
         
         
         
         
         
         
         


       
    
       
    
    
    
    
    
    
    
    
       



       
  
       
  
  
  
  
  
  
  
  
       



         