# TCL File Generated by Component Editor 16.1
# Fri Feb 8 16:31:53 GMT+08:00 2018
# DO NOT MODIFY


# 
# harden_rx "unpack" v1.0
# Royce Ai Yu Pan 2018.05.16.16:31:53 
# 
# 


# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1

# 
# module # 
# connection point avalon_streaming_sink
# 
                
# 
set_module_property DESCRIPTION " distributor"
set_module_property NAME unpack
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "FACC 5G"
set_module_property AUTHOR  PENG FAN
set_module_property DISPLAY_NAME unpack
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL unpack
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false

add_fileset_file unpack.sv VERILOG PATH unpack.sv TOP_LEVEL_FILE
add_fileset_file avlst_64to8.sv SYSTEM_VERILOG PATH avlst_64to8.sv
add_fileset_file util_packfifo.sv SYSTEM_VERILOG PATH util_packfifo.sv
add_fileset_file dl_distribt.sv SYSTEM_VERILOG PATH dl_distribt.sv


# 
# parameters SCS_NUM
# 
add_parameter SCS_NUM INTEGER 3276                        
set_parameter_property SCS_NUM DEFAULT_VALUE 3276         
set_parameter_property SCS_NUM DISPLAY_NAME SCS_NUM       
set_parameter_property SCS_NUM TYPE INTEGER                
set_parameter_property SCS_NUM UNITS None                  
set_parameter_property SCS_NUM HDL_PARAMETER true          

   
#                                                                                  
# connection point clk_in                                                         
#                                                                                  
add_interface clk_in clock end                                                    
set_interface_property clk_in clockRate 0                                         
set_interface_property clk_in ENABLED true                                        
set_interface_property clk_in EXPORT_OF ""                                        
set_interface_property clk_in PORT_NAME_MAP ""                                    
set_interface_property clk_in CMSIS_SVD_VARIABLES ""                              
set_interface_property clk_in SVD_ADDRESS_GROUP ""                                
                                                                                   
add_interface_port clk_in clk_in clk Input 1                                 

#                                                                                  
# connection point clk_rd                                                         
#                                                                                  
add_interface clk_rd clock end                                                    
set_interface_property clk_rd clockRate 0                                         
set_interface_property clk_rd ENABLED true                                        
set_interface_property clk_rd EXPORT_OF ""                                        
set_interface_property clk_rd PORT_NAME_MAP ""                                    
set_interface_property clk_rd CMSIS_SVD_VARIABLES ""                              
set_interface_property clk_rd SVD_ADDRESS_GROUP ""                                
                                                                                   
add_interface_port clk_rd clk_rd clk Input 1                                                                                                                                                                                                                    
                                                              
#                                                                      
# connection point rst_n                                               
# rst_n                                                                
add_interface rst_n reset end                                          
set_interface_property rst_n associatedClock clk_in                   
set_interface_property rst_n synchronousEdges DEASSERT                 
set_interface_property rst_n ENABLED true                              
set_interface_property rst_n EXPORT_OF ""                              
set_interface_property rst_n PORT_NAME_MAP ""                          
set_interface_property rst_n CMSIS_SVD_VARIABLES ""                    
set_interface_property rst_n SVD_ADDRESS_GROUP ""                      
                                                                       
add_interface_port rst_n rst_n reset_n Input 1     

################################################################

                    
                                                                       

#################################################################   
#                    connect harden_tx                          #   
#################################################################
 
add_interface pdsch_ante_0 conduit end                                                
set_interface_property pdsch_ante_0 associatedClock ""                                
set_interface_property pdsch_ante_0 associatedReset ""                                
set_interface_property pdsch_ante_0 ENABLED true                                      
set_interface_property pdsch_ante_0 EXPORT_OF ""                                      
set_interface_property pdsch_ante_0 PORT_NAME_MAP ""                                  
set_interface_property pdsch_ante_0 CMSIS_SVD_VARIABLES ""                            
set_interface_property pdsch_ante_0 SVD_ADDRESS_GROUP ""                              
                                                                                      
add_interface_port pdsch_ante_0  dout_ante0_valid	  valid	 Output 1                      
add_interface_port pdsch_ante_0  dout_ante0_sop     sop    Output 1                       
add_interface_port pdsch_ante_0  dout_ante0_eop     eop    Output 1                      
add_interface_port pdsch_ante_0  dout_ante0_data    data   Output 64 
add_interface_port pdsch_ante_0  symbol_ante0_index symbol Output 4  
add_interface_port pdsch_ante_0  slot_ante0_index   slot   Output 8  
add_interface_port pdsch_ante_0  frame_ante0_index  frame  Output 10 
     

add_interface pdsch_ante_1 conduit end                                          
set_interface_property pdsch_ante_1 associatedClock ""                          
set_interface_property pdsch_ante_1 associatedReset ""                          
set_interface_property pdsch_ante_1 ENABLED true                                
set_interface_property pdsch_ante_1 EXPORT_OF ""                                
set_interface_property pdsch_ante_1 PORT_NAME_MAP ""                            
set_interface_property pdsch_ante_1 CMSIS_SVD_VARIABLES ""                      
set_interface_property pdsch_ante_1 SVD_ADDRESS_GROUP ""                        
                                                                                
add_interface_port pdsch_ante_1  dout_ante1_valid	valid	Output 1                
add_interface_port pdsch_ante_1  dout_ante1_sop   sop   Output 1                
add_interface_port pdsch_ante_1  dout_ante1_eop   eop   Output 1                
add_interface_port pdsch_ante_1  dout_ante1_data  data  Output 64               
add_interface_port pdsch_ante_1  symbol_ante1_index symbol Output 4         
add_interface_port pdsch_ante_1  slot_ante1_index   slot   Output 8         
add_interface_port pdsch_ante_1  frame_ante1_index  frame  Output 10        
                                                                              
                                                                                                           
# 
# connection point avalon_streaming_sink
# 
add_interface xgmac_avalon_st_tx avalon_streaming end                                 
set_interface_property xgmac_avalon_st_tx dataBitsPerSymbol 8                         
set_interface_property xgmac_avalon_st_tx associatedClock clk_in                      
set_interface_property xgmac_avalon_st_tx associatedReset rst_n                       
set_interface_property xgmac_avalon_st_tx errorDescriptor ""                          
set_interface_property xgmac_avalon_st_tx firstSymbolInHighOrderBits true             
set_interface_property xgmac_avalon_st_tx maxChannel 0                                
set_interface_property xgmac_avalon_st_tx readyLatency 0                              
set_interface_property xgmac_avalon_st_tx ENABLED true                                
set_interface_property xgmac_avalon_st_tx EXPORT_OF ""                                
set_interface_property xgmac_avalon_st_tx PORT_NAME_MAP ""                            
set_interface_property xgmac_avalon_st_tx CMSIS_SVD_VARIABLES ""                      
set_interface_property xgmac_avalon_st_tx SVD_ADDRESS_GROUP ""                        
                                                                                      
 add_interface_port xgmac_avalon_st_tx din_sop startofpacket Input 1                  
 add_interface_port xgmac_avalon_st_tx din_eop endofpacket Input 1                    
 add_interface_port xgmac_avalon_st_tx din_valid valid Input 1                        
 add_interface_port xgmac_avalon_st_tx din_empty empty Input 3                        
 add_interface_port xgmac_avalon_st_tx din_data data Input 64                         
 add_interface_port xgmac_avalon_st_tx din_error error Input 6                        
 add_interface_port xgmac_avalon_st_tx mac_avalon_st_tx_ready ready Output 1          
   
      
 #                                                                                                     
 # connection point gmac_avalon_st_rx                                                                 
 #                                                                                                     
 add_interface gmac_avalon_st_rx avalon_streaming start                                               
 set_interface_property gmac_avalon_st_rx associatedClock clk_rd                                  
 set_interface_property gmac_avalon_st_rx associatedReset rst_n                               
 set_interface_property gmac_avalon_st_rx dataBitsPerSymbol 8                                         
 set_interface_property gmac_avalon_st_rx errorDescriptor ""                                          
 set_interface_property gmac_avalon_st_rx firstSymbolInHighOrderBits true                             
 set_interface_property gmac_avalon_st_rx maxChannel 0                                               
 set_interface_property gmac_avalon_st_rx readyLatency 0                                          
 set_interface_property gmac_avalon_st_rx ENABLED true                                            
 set_interface_property gmac_avalon_st_rx EXPORT_OF ""                                            
 set_interface_property gmac_avalon_st_rx PORT_NAME_MAP ""                                        
 set_interface_property gmac_avalon_st_rx CMSIS_SVD_VARIABLES ""                                  
 set_interface_property gmac_avalon_st_rx SVD_ADDRESS_GROUP ""                                    
                                                                                                   
 add_interface_port gmac_avalon_st_rx dout_sop startofpacket Output 1                             
 add_interface_port gmac_avalon_st_rx dout_eop endofpacket Output 1                               
 add_interface_port gmac_avalon_st_rx dout_valid valid Output 1                                   
 add_interface_port gmac_avalon_st_rx dout_empty empty Output 3                                   
 add_interface_port gmac_avalon_st_rx dout_data data Output 8                                                                     
 add_interface_port gmac_avalon_st_rx din_ready ready Input 1                                       


     

                                                         




      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      

 
 
 






























           
            
           
            
            
            
            
            
            
            
            
           
             
           