# TCL File Generated by Component Editor 16.1
# Fri Feb 8 16:31:53 GMT+08:00 2018
# DO NOT MODIFY


# 
# harden_rx "pack" v1.0
# Royce Ai Yu Pan 2018.05.16.16:31:53 
# 
# 


# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1

# 
# module harden_rx
# 
set_module_property DESCRIPTION "This submodule schedules the transmission order of various packets destined for the BBU."
set_module_property NAME pack
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "FACC 5G"
set_module_property AUTHOR  Royce Ai Yu Pan
set_module_property DISPLAY_NAME pack
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pack
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false

add_fileset_file pack.sv VERILOG PATH pack.sv TOP_LEVEL_FILE
add_fileset_file pusch_packet.sv VERILOG PATH pusch_packet.sv
add_fileset_file timing_packet.v SYSTEM_VERILOG PATH timing_packet.v
add_fileset_file util_arbitmux.sv SYSTEM_VERILOG PATH util_arbitmux.sv 
add_fileset_file avlst_32to64.sv SYSTEM_VERILOG PATH avlst_32to64.sv           
add_fileset_file util_packfifo.sv SYSTEM_VERILOG PATH util_packfifo.sv         

# 
# parameters
# 


#  SC_NUM                                                       
add_parameter SC_NUM INTEGER 3300                               
set_parameter_property SC_NUM DEFAULT_VALUE 3300                
set_parameter_property SC_NUM DISPLAY_NAME SC_NUM               
set_parameter_property SC_NUM TYPE INTEGER                      
set_parameter_property SC_NUM UNITS None                        
set_parameter_property SC_NUM HDL_PARAMETER true                
                                                                
#  PACKET_ANTE_NUM                                                          
add_parameter PACKET_ANTE_NUM INTEGER 1                                     
set_parameter_property PACKET_ANTE_NUM DEFAULT_VALUE 1                      
set_parameter_property PACKET_ANTE_NUM DISPLAY_NAME PACKET_ANTE_NUM         
set_parameter_property PACKET_ANTE_NUM TYPE INTEGER                         
set_parameter_property PACKET_ANTE_NUM UNITS None                           
set_parameter_property PACKET_ANTE_NUM HDL_PARAMETER true                   


#  ANTE_NUM                                                 
add_parameter ANTE_NUM INTEGER 2                         
set_parameter_property ANTE_NUM DEFAULT_VALUE 2         
set_parameter_property ANTE_NUM DISPLAY_NAME ANTE_NUM       
set_parameter_property ANTE_NUM TYPE INTEGER                
set_parameter_property ANTE_NUM UNITS None                  
set_parameter_property ANTE_NUM HDL_PARAMETER true          

#  ARBIT_LEVEL                                                 
add_parameter ARBIT_LEVEL INTEGER 2                         
set_parameter_property ARBIT_LEVEL DEFAULT_VALUE 2         
set_parameter_property ARBIT_LEVEL DISPLAY_NAME ARBIT_LEVEL       
set_parameter_property ARBIT_LEVEL TYPE INTEGER                
set_parameter_property ARBIT_LEVEL UNITS None                  
set_parameter_property ARBIT_LEVEL HDL_PARAMETER true          

#  DATA_WIDTH                                                 
add_parameter DATA_WIDTH INTEGER 64                         
set_parameter_property DATA_WIDTH DEFAULT_VALUE 64         
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH       
set_parameter_property DATA_WIDTH TYPE INTEGER                
set_parameter_property DATA_WIDTH UNITS None                  
set_parameter_property DATA_WIDTH HDL_PARAMETER true          

   
#                                                                                  
# connection point eth_clk                                                         
#                                                                                  
add_interface eth_clk clock end                                                    
set_interface_property eth_clk clockRate 0                                         
set_interface_property eth_clk ENABLED true                                        
set_interface_property eth_clk EXPORT_OF ""                                        
set_interface_property eth_clk PORT_NAME_MAP ""                                    
set_interface_property eth_clk CMSIS_SVD_VARIABLES ""                              
set_interface_property eth_clk SVD_ADDRESS_GROUP ""                                
                                                                                   
add_interface_port eth_clk clk clk Input 1    

#                                                             
# connection point clk_1g                                     
#                                                             
add_interface clk_1g clock end                                
set_interface_property clk_1g clockRate 0                     
set_interface_property clk_1g ENABLED true                    
set_interface_property clk_1g EXPORT_OF ""                    
set_interface_property clk_1g PORT_NAME_MAP ""                
set_interface_property clk_1g CMSIS_SVD_VARIABLES ""          
set_interface_property clk_1g SVD_ADDRESS_GROUP ""            
                                                              
add_interface_port clk_1g clk_1g clk Input 1                  
                                                                                                                                                        
                                                                           
#                                                                      
# connection point rst_n                                               
# rst_n                                                                
add_interface rst_n reset end                                          
set_interface_property rst_n associatedClock eth_clk                  
set_interface_property rst_n synchronousEdges DEASSERT                 
set_interface_property rst_n ENABLED true                              
set_interface_property rst_n EXPORT_OF ""                              
set_interface_property rst_n PORT_NAME_MAP ""                          
set_interface_property rst_n CMSIS_SVD_VARIABLES ""                    
set_interface_property rst_n SVD_ADDRESS_GROUP ""                      
                                                                       
add_interface_port rst_n rst_n reset_n Input 1                         
                                                                       

#################################################################              
# irq_1ms from harden_sync                                                     
                                                                                                                          
add_interface irq_1ms conduit end                                              
set_interface_property irq_1ms associatedClock  ""                             
set_interface_property irq_1ms associatedReset ""                              
set_interface_property irq_1ms ENABLED true                                    
set_interface_property irq_1ms EXPORT_OF ""                                    
set_interface_property irq_1ms PORT_NAME_MAP ""                                
set_interface_property irq_1ms CMSIS_SVD_VARIABLES ""                          
set_interface_property irq_1ms SVD_ADDRESS_GROUP ""                            
                                                                               
add_interface_port irq_1ms irq_1ms export Input 1                              
                                                                               
# index from harden_sync

add_interface sync_index conduit end                             
set_interface_property sync_index associatedClock  ""          
set_interface_property sync_index associatedReset ""           
set_interface_property sync_index ENABLED true                 
set_interface_property sync_index EXPORT_OF ""                 
set_interface_property sync_index PORT_NAME_MAP ""             
set_interface_property sync_index CMSIS_SVD_VARIABLES ""       
set_interface_property sync_index SVD_ADDRESS_GROUP ""         
                                                                 
add_interface_port sync_index timing_slot_index  slot Input 8    
add_interface_port sync_index timing_frame_index frame Input 16    

#                                                                               
# mac_addr                                                                      
#                                                                               
add_interface mac_addr conduit end                                                                  
set_interface_property mac_addr associatedClock  ""                                            
set_interface_property mac_addr associatedReset ""                                                
set_interface_property mac_addr ENABLED true                                                      
set_interface_property mac_addr EXPORT_OF ""                                                       
set_interface_property mac_addr PORT_NAME_MAP ""                                
set_interface_property mac_addr CMSIS_SVD_VARIABLES ""                          
set_interface_property mac_addr SVD_ADDRESS_GROUP ""                            
                                                                                
add_interface_port mac_addr dest_addr_l export_0 Input 32                      
add_interface_port mac_addr dest_addr_h export_1 Input 32                      
add_interface_port mac_addr sour_addr_l export_2 Input 32                                  
add_interface_port mac_addr sour_addr_h export_3 Input 32                                     
                                                                                           
 
add_interface pusch_ante_0 conduit end                                   
set_interface_property pusch_ante_0 associatedClock ""                   
set_interface_property pusch_ante_0 associatedReset ""                   
set_interface_property pusch_ante_0 ENABLED true                         
set_interface_property pusch_ante_0 EXPORT_OF ""                         
set_interface_property pusch_ante_0 PORT_NAME_MAP ""                     
set_interface_property pusch_ante_0 CMSIS_SVD_VARIABLES ""               
set_interface_property pusch_ante_0 SVD_ADDRESS_GROUP ""                 
                                
add_interface_port pusch_ante_0  ante0_block_used   used Input  4              
add_interface_port pusch_ante_0  ante0_rx_rd_en     rd_req  Output 1              
add_interface_port pusch_ante_0  ante0_rx_data      data   Input  64             
add_interface_port pusch_ante_0  ante0_rx_valid     valid  Input  1              
add_interface_port pusch_ante_0  ante0_gain_factor  exp    Input  16             
add_interface_port pusch_ante_0  ante0_symbol_index symbol Input  8              
add_interface_port pusch_ante_0  ante0_slot_index   slot   Input  8              
add_interface_port pusch_ante_0  ante0_frame_index  frame  Input  10             
                                                                                 

add_interface pusch_ante_1 conduit end                             
set_interface_property pusch_ante_1 associatedClock ""             
set_interface_property pusch_ante_1 associatedReset ""             
set_interface_property pusch_ante_1 ENABLED true                   
set_interface_property pusch_ante_1 EXPORT_OF ""                   
set_interface_property pusch_ante_1 PORT_NAME_MAP ""               
set_interface_property pusch_ante_1 CMSIS_SVD_VARIABLES ""         
set_interface_property pusch_ante_1 SVD_ADDRESS_GROUP ""        
   
add_interface_port pusch_ante_1  ante1_block_used   used Input  4             
add_interface_port pusch_ante_1  ante1_rx_rd_en     rd_req  Output 1             
add_interface_port pusch_ante_1  ante1_rx_data      data   Input  64            
add_interface_port pusch_ante_1  ante1_rx_valid     valid  Input  1             
add_interface_port pusch_ante_1  ante1_gain_factor  exp    Input  16            
add_interface_port pusch_ante_1  ante1_symbol_index symbol Input  8             
add_interface_port pusch_ante_1  ante1_slot_index   slot   Input  8             
add_interface_port pusch_ante_1  ante1_frame_index  frame  Input  10            
                                                                                                                                                                                                          
#                                                                                                     
# connection point xgmac_avalon_st_rx                                                                 
#                                                                                                     
add_interface xgmac_avalon_st_rx avalon_streaming start                                               
set_interface_property xgmac_avalon_st_rx associatedClock eth_clk                                  
set_interface_property xgmac_avalon_st_rx associatedReset rst_n                              
set_interface_property xgmac_avalon_st_rx dataBitsPerSymbol 8                                         
set_interface_property xgmac_avalon_st_rx errorDescriptor ""                                          
set_interface_property xgmac_avalon_st_rx firstSymbolInHighOrderBits true                             
set_interface_property xgmac_avalon_st_rx maxChannel 0                                               
set_interface_property xgmac_avalon_st_rx readyLatency 0                                          
set_interface_property xgmac_avalon_st_rx ENABLED true                                            
set_interface_property xgmac_avalon_st_rx EXPORT_OF ""                                            
set_interface_property xgmac_avalon_st_rx PORT_NAME_MAP ""                                        
set_interface_property xgmac_avalon_st_rx CMSIS_SVD_VARIABLES ""                                  
set_interface_property xgmac_avalon_st_rx SVD_ADDRESS_GROUP ""                                    
                                                                                                  
add_interface_port xgmac_avalon_st_rx dout_sop startofpacket Output 1                             
add_interface_port xgmac_avalon_st_rx dout_eop endofpacket Output 1                               
add_interface_port xgmac_avalon_st_rx dout_valid valid Output 1                                   
add_interface_port xgmac_avalon_st_rx dout_empty empty Output 3                                   
add_interface_port xgmac_avalon_st_rx dout_data data Output 64 
add_interface_port xgmac_avalon_st_rx dout_ready ready Input 1                                   
                                                                                                  

#                                                                                                   
# connection point gmac_avalon_st_rx                                                                
#                                                                                                      
add_interface gmac_avalon_st_rx avalon_streaming end                                                   
set_interface_property gmac_avalon_st_rx associatedClock clk_1g                                        
set_interface_property gmac_avalon_st_rx associatedReset rst_n                                         
set_interface_property gmac_avalon_st_rx dataBitsPerSymbol 8                                           
set_interface_property gmac_avalon_st_rx errorDescriptor ""                                            
set_interface_property gmac_avalon_st_rx firstSymbolInHighOrderBits true                               
set_interface_property gmac_avalon_st_rx maxChannel 0                                                  
set_interface_property gmac_avalon_st_rx readyLatency 0                                                
set_interface_property gmac_avalon_st_rx ENABLED true                                                     
set_interface_property gmac_avalon_st_rx EXPORT_OF ""                                                    
set_interface_property gmac_avalon_st_rx PORT_NAME_MAP ""                                           
set_interface_property gmac_avalon_st_rx CMSIS_SVD_VARIABLES ""                                     
set_interface_property gmac_avalon_st_rx SVD_ADDRESS_GROUP ""                                            
                                                                                                    
add_interface_port gmac_avalon_st_rx din_sop startofpacket Input 1                                                                                           
add_interface_port gmac_avalon_st_rx din_eop endofpacket Input 1                                    
add_interface_port gmac_avalon_st_rx din_valid valid Input 1                                        
add_interface_port gmac_avalon_st_rx din_empty empty Input 2                                        
add_interface_port gmac_avalon_st_rx din_data data Input 32                                         
                                                                                                          
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      

 
 
 






























           
            
           
            
            
            
            
            
            
            
            
           
             
           